title: Rawazer's awesome blog
author: Rawazer, of course
email: rawazer@rawazer.rawazer
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A description. But, I mean, a really DESCRIPTIVE description. One which
  describes the blog to all it's little detailed descriptions. Only describing
  so much to see how many lines look.

# social links
twitter_username: i-have-none # DO NOT include the @ character, or else the build will fail!
github_username:  rawazer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
